[test] Server init
moevm/MSE-2023-image-ecology-12 pull request #22
Opened 2023-03-07 17:02 UTC by youngwow

2023-03-07 17:24 UTC, youngwow commented on backend/db.py
> +import os
Необходимо будет удалить

2023-03-07 17:28 UTC, youngwow commented on backend/db.py
> +        db = g._database = client.get_database('ecologyDB')
Необходимо будет заменить на:
db_url = os.environ['DB_URI'] if ('DB_URI' in os.environ) else "mongodb://localhost:27017/db"
client = pymongo.MongoClient(db_url)
db = g._database = client.get_database(<Название БД>)

2023-03-08 09:55 UTC, Saprigenie requested changes
Необходимо соблюсти структуру приложения, предложенную @vladDotH, и перенести реализацию сервера из папки backend в папку server.

2023-03-08 16:44 UTC, Saprigenie reviewed
Выглядит здорово, но оставил несколько вопросов по реализации.

2023-03-08 16:44 UTC, Saprigenie commented on backend/app.py
> +    CORS(app)
Может к базе данных подключаться при инициализации сервера и сразу класть объект базы данных в глобальный контекст g, как ты это делаешь в функциях, находящихся в db.py?

2023-03-08 16:44 UTC, Saprigenie commented on backend/db.py
> +from gridfs import GridFS
flask_pymongo вроде позволяет более просто работать с базой данных и по умолчанию многие его функции работают с GridFS или его функционала не хватает, поэтому ты решил использовать pymongo и flask по отдельности?

2023-03-08 16:44 UTC, Saprigenie commented on backend/routes/images_bp.py
> +    return jsonify(images)
По идее, search_images действительно уже должна включать данный функционал.

2023-03-11 16:54 UTC, youngwow commented
> Необходимо соблюсти структуру приложения, предложенную @vladDotH, и перенести реализацию сервера из папки backend в папку server.

Готово

2023-03-11 16:55 UTC, youngwow commented on backend/routes/images_bp.py
> +    return jsonify(images)
Хорошо, согласен.

2023-03-11 17:35 UTC, youngwow commented on backend/app.py
> +    CORS(app)
Создал функцию init_db https://github.com/moevm/MSE-2023-image-ecology-12/pull/22/commits/71ec479574fba3af6063a0a8a379c90be354bf16#diff-38123374db6dc447d116c96d02ab25c32be607251adedf56375b7a679b620b8cR7

Чтобы при создании приложения была инициализация базы данных: https://github.com/moevm/MSE-2023-image-ecology-12/pull/22/commits/71ec479574fba3af6063a0a8a379c90be354bf16#diff-675fd40609ae40556a55940d36663ec1f152ec31295f3daa0846c26c72723c4eR12

Сделал в точности как советует документация по Flask: https://flask.palletsprojects.com/en/2.2.x/appcontext/

Изначально так хотел сделать, но были ошибки, а сейчас только что понял как их решить.

2023-03-11 17:37 UTC, youngwow commented
Также поменял docker-compose.yml https://github.com/moevm/MSE-2023-image-ecology-12/pull/22/commits/25be8576b6374ee42fe1fb14ce29e5121639a676#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R12

2023-03-11 17:53 UTC, youngwow commented
Если что, то инициализацию worker'а тоже сюда добавил. Но там есть ошибки:
0. GET, а POST
1. ID прям прописано, а не из данных от POST запроса: https://github.com/moevm/MSE-2023-image-ecology-12/pull/22/commits/25be8576b6374ee42fe1fb14ce29e5121639a676#diff-fb5f548f92c5409359a77ea8f306107ba59b397cc20a1848daa31cf34bcd2fabR25
2. Необходимо преобразовать numpy.array в байты: https://github.com/moevm/MSE-2023-image-ecology-12/pull/22/commits/25be8576b6374ee42fe1fb14ce29e5121639a676#diff-fb5f548f92c5409359a77ea8f306107ba59b397cc20a1848daa31cf34bcd2fabR62

2023-03-12 22:44 UTC, Saprigenie approved these changes

2023-03-12 22:49 UTC, merged