[test] Client update
moevm/MSE-2023-image-ecology-12 pull request #30
Opened 2023-03-18 14:54 UTC by vladDotH

2023-03-20 22:03 UTC, dart-mih approved these changes

2023-03-20 22:03 UTC, dart-mih commented on client/src/types/queue.ts
> +  progress: number;
Хм.... вообще, выглядит прогресс классно, но мы как-то не учитывали это вообще... Предполагается, что прогресс хранится в базе данных и обновляется по мере обработки кусочков?

2023-03-20 22:08 UTC, vladDotH commented on client/src/ag-grid/localization.ts
> +  applyFilter: "Применить фильтр...",
скопировал из локализации 
https://gist.github.com/artbutko/a3927592029873b41c8149474c45e4b7

2023-03-20 22:09 UTC, vladDotH commented on client/src/components/routes/maps/MapsListComponent.vue
> +  { headerName: "Имя", field: "name", flex: 3 },
это нужно чтобы его нельзя было сильно сжать, либо на маленьких экранах он не сожмётся меньше минимального размер

2023-03-20 22:10 UTC, vladDotH commented on client/src/types/queue.ts
> +  progress: number;
ну я возможно получить прогресс в процентах, в конце концов отслеживание прогресса вроде как одна из задач

2023-03-21 08:54 UTC, dart-mih commented on client/src/types/queue.ts
> +  progress: number;
Хм
Тогда предлагаю после каждого обработанного фрагмента обновлять процент прогресса в бд при работе воркера

2023-03-21 08:56 UTC, vladDotH commented on client/src/components/routes/maps/MapsListComponent.vue
> +  { headerName: "Имя", field: "name", flex: 3 },
теперь есть

2023-03-21 08:58 UTC, dart-mih commented on client/src/ag-grid/localization.ts
> +  applyFilter: "Применить фильтр...",
Может, просто подчистить лишнее, чтобы не было просто так висящих переводов? Мало ли, что там потом накрутится поверх

2023-03-21 09:01 UTC, dart-mih approved these changes

2023-03-21 10:27 UTC, Saprigenie requested changes

2023-03-21 10:27 UTC, Saprigenie commented on client/src/components/routes/anomaly/AnomalyComponent.vue
> +      />
Здесь предполагается карта, на которой выявлена аномалия с центровкой на контуре этой аномалии?

2023-03-21 10:27 UTC, Saprigenie commented on client/src/components/routes/anomaly/AnomalyComponent.vue
> +const columnDefs: ColDef<AnomalyInfo>[] = [
Функция getAnomalyData возвращает anomalyData тип, который является расширением AnomalyInfo. Здесь используется anomalyData, чтобы было больше данных и была возможность отобразить карту и аномалию?

2023-03-21 10:27 UTC, Saprigenie commented on client/src/types/reports.ts
> +  mapId: number;
Тот же вопрос про mapId

2023-03-21 10:27 UTC, Saprigenie commented on client/src/components/routes/upload/UploadComponent.vue
> +          accept=".tiff,.jpg,.png"
Хмммм.... accept jpg и png? 2 этих формата не имеют информацию о геопривязке, обработать их можно, но на карте отобразить по нормальному не получиться (вместе с OpenStreetMap в подложке). Ты предполагаешь такие изображения все-таки обрабатывать, но для них уникальное отображение создавать?

2023-03-21 15:05 UTC, vladDotH commented on client/src/ag-grid/localization.ts
> +  applyFilter: "Применить фильтр...",
какие висящие переводы, там просто комментарии к группам имён так написаны

2023-03-25 10:07 UTC, vladDotH commented on client/src/components/routes/anomaly/AnomalyComponent.vue
>      headerName: "Дата обнаружения",
добавил

2023-03-25 10:09 UTC, vladDotH commented on client/src/api/index.ts
> +const port = import.meta.env.CLIENT_SERVER_PORT ?? "3000";
добавил в docker-compose

2023-03-25 10:21 UTC, vladDotH commented on client/src/api/index.ts
> +const port = import.meta.env.CLIENT_SERVER_PORT ?? "3000";
поменял

2023-03-25 10:28 UTC, vladDotH commented on client/src/types/anomalies.ts
> +  mapId: number;
сделал string

2023-03-25 10:28 UTC, vladDotH commented on client/src/types/maps.ts
> +  id: number;
https://github.com/moevm/MSE-2023-image-ecology-12/pull/30#discussion_r1148345745

2023-03-25 10:28 UTC, vladDotH commented on client/src/components/routes/anomaly/AnomalyComponent.vue
> +      />
да, пока что заглушка с картой

2023-03-25 10:29 UTC, vladDotH commented on client/src/types/reports.ts
> +  mapId: number;
https://github.com/moevm/MSE-2023-image-ecology-12/pull/30#discussion_r1148345745

2023-03-25 10:38 UTC, vladDotH commented on client/src/components/routes/anomalies/api.ts
> +}
в таблице аномалий просто нету ссылки на карту, а вот в самой аномалии есть, поэтому не думаю что имеет смысл. В любом случае в рантайме никаких проверок типов нету, поэтому даже если лишние поля придут, они всё равно использоваться не будут.

2023-03-25 10:39 UTC, vladDotH commented on client/src/components/routes/anomaly/AnomalyComponent.vue
> +const columnDefs: ColDef<AnomalyInfo>[] = [
ну что-то типо того, просто разные интерфейсы для разных запросов

2023-03-25 10:50 UTC, Saprigenie approved these changes

2023-03-25 10:57 UTC, merged