[test] Geotiff fragments display on client
moevm/MSE-2023-image-ecology-12 pull request #44
Opened 2023-03-20 19:00 UTC by Saprigenie

2023-03-28 09:19 UTC, dart-mih approved these changes

2023-03-28 10:26 UTC, Saprigenie commented on worker/app.py
> +            if (len(path) >= 2):
Когда gdal2tiles нарезает фото на фрагменты, то он не только кладет сами фрагменты по пути /{z}/{x}/{y}.png, но и добавляет несколько дополнительных файлов в корень (данные геопривязки, html с leaflet-ом для теста), это условие игнорирует эти файлы.

2023-03-28 10:30 UTC, dart-mih commented on worker/app.py
> +            if (len(path) >= 2):
А... Добавь небольшой комментарий тогда, а то потом никто про эту не вспомнит)

2023-03-28 11:02 UTC, Saprigenie commented on worker/app.py
> +            if (len(path) >= 2):
Добавил.

2023-03-29 22:56 UTC, dart-mih commented on client/src/components/routes/upload/UploadComponent.vue
> +function submit(data: { files: { name: string; file: File }[]; name: string }) {
Что-то не так с типами данных - сборка крашится

2023-03-30 01:15 UTC, Saprigenie commented on client/src/components/routes/upload/UploadComponent.vue
> +function submit(data: { files: { name: string; file: File }[]; name: string }) {
При merge слетело исправление этой ошибки, сейчас все исправлено.

2023-03-30 01:41 UTC, Saprigenie commented on client/src/components/routes/upload/UploadComponent.vue
> +function submit(data: { files: { name: string; file: File }[]; name: string }) {
Теперь должно собираться.

2023-03-30 01:41 UTC, Saprigenie commented on client/package.json
Спасибо за совет )

2023-03-30 17:33 UTC, vladDotH requested changes

2023-03-30 17:33 UTC, vladDotH commented on client/src/components/map/MapDisplay.vue
В чём отличие этого файла от [components/common/MapDisplay](https://github.com/moevm/MSE-2023-image-ecology-12/pull/44/files#diff-26ec2bed3410126cd8d241d437c70dce24e59e077193eacc2332843a7b1a3962) ?

2023-03-30 18:11 UTC, vladDotH requested changes

2023-03-30 18:22 UTC, vladDotH requested changes

2023-03-30 18:22 UTC, vladDotH commented on client/package-lock.json
не надо удалять package-lock, это не просто служебный файл, он содержит информацию о конкретных версиях библиотек, что может понадобится для ci/cd пайплайна (npm ci)

2023-03-30 18:28 UTC, Saprigenie commented on client/package-lock.json
При наличии данного файла у меня не собирался клиент.

2023-03-30 21:35 UTC, Saprigenie commented on client/src/components/common/map/MapDisplay.vue
> +    var osm = L.tileLayer("https://{s}.tile.osm.org/{z}/{x}/{y}.png", {attribution: "&copy; <a href='http://osm.org/copyright'>OpenStreetMap</a> contributors"});
Заменил на let-ы + добавил некоторые типы.

2023-03-30 21:35 UTC, Saprigenie commented on client/src/components/map/api.ts
> +  });
Исправил избыточность.

2023-03-30 21:36 UTC, Saprigenie commented on client/src/components/routes/maps/api.ts
> +  });
Так же исправлено.

2023-03-30 21:36 UTC, Saprigenie commented on client/package-lock.json
Сгенерировал новый package-lock.json.

2023-03-31 07:43 UTC, vladDotH approved these changes

2023-03-31 07:45 UTC, merged