[test] Docker best pr
moevm/MSE-2023-image-ecology-12 pull request #79
Opened 2023-04-13 11:28 UTC by Saprigenie

2023-04-14 20:28 UTC, dart-mih requested changes

2023-04-14 20:28 UTC, dart-mih commented on worker/Dockerfile
> +RUN apt-get update && apt install -y python3-pip
pip-у бы версию еще
может и питону тоже, хз

2023-04-16 11:13 UTC, Saprigenie commented on worker/Dockerfile
> +RUN apt-get update && apt install -y python3-pip
Питон в образе уже встроен и имеет конкретную версию, а версию pip добавил.

2023-04-16 11:15 UTC, dart-mih approved these changes

2023-04-16 11:15 UTC, merged