[test] Celery queueing
moevm/MSE-2023-image-ecology-12 pull request #89
Opened 2023-04-19 23:08 UTC by vladDotH

2023-04-21 20:12 UTC, Saprigenie requested changes

2023-04-21 20:12 UTC, Saprigenie commented on server/app/routes/images_bp.py
> +mapFs = LocalProxy(get_map_fs)
```suggestion
tile_fs = LocalProxy(get_tile_fs)
map_fs = LocalProxy(get_map_fs)
```
Предложение все переменные на сервере именовать в едином стиле.

2023-04-21 20:12 UTC, Saprigenie commented on server/requirements.txt
>  requests==2.25.1
```suggestion
```
Зависимость ушла после создания очереди в selery.

2023-04-21 20:12 UTC, Saprigenie commented on worker/app/db.py
> +    tileFs: GridFS
```suggestion
    map_fs: GridFS
    tile_fs: GridFS
```
То же самое.

2023-04-21 20:12 UTC, Saprigenie commented on worker/requirements.txt
> +requests==2.25.1
```suggestion
```
Не используется.

2023-04-21 20:59 UTC, vladDotH commented on server/app/routes/images_bp.py
> +mapFs = LocalProxy(get_map_fs)
✔️

2023-04-21 20:59 UTC, vladDotH commented on server/requirements.txt
>  requests==2.25.1
✔️

2023-04-21 20:59 UTC, vladDotH commented on worker/app/db.py
> +    tileFs: GridFS
✔️

2023-04-21 20:59 UTC, vladDotH commented on worker/requirements.txt
> +requests==2.25.1
✔️

2023-04-21 21:08 UTC, Saprigenie requested changes

2023-04-21 21:08 UTC, Saprigenie commented on docker-compose.yml
> +  celery:
```suggestion
  celery:
    container_name: celery
```
Чтобы название контейнера были единообразными.

2023-04-21 21:13 UTC, vladDotH commented on docker-compose.yml
> +  celery:
✓

2023-04-21 21:14 UTC, Saprigenie approved these changes

2023-04-22 12:00 UTC, Saprigenie approved these changes

2023-04-22 12:53 UTC, dart-mih approved these changes

2023-04-22 12:53 UTC, dart-mih commented on worker/app/config.py
> +MONGO_URI = environ.get('MONGO_URI', "mongodb://localhost:27017/db")
Насколько вообще по зависимостям можно/есть смысл сделать один большой конфиг для почти всех строковых переменных, в том числе для переменных среды?

2023-04-22 13:12 UTC, vladDotH commented on worker/app/config.py
> +MONGO_URI = environ.get('MONGO_URI', "mongodb://localhost:27017/db")
ну в config пока что переменные среды только извлекаются

2023-04-22 16:16 UTC, merged