[test] Worker slicer for tiles selery
moevm/MSE-2023-image-ecology-12 pull request #98
Opened 2023-04-23 10:26 UTC by Saprigenie

2023-04-23 21:41 UTC, vladDotH commented
просто напомню что `celery` пишется через `c`...

2023-04-23 21:45 UTC, Saprigenie commented
https://github.com/moevm/MSE-2023-image-ecology-12/pull/98#issuecomment-1519175130 Ветку переименовывать не буду, так как pull request-ы закроются ))

2023-04-23 21:46 UTC, vladDotH approved these changes

2023-04-23 21:46 UTC, vladDotH commented on client/src/components/common/map/MapDisplay.vue
> +let forestPolygonArr: number[][][] | undefined = await getForestPolygon(props.id);
typescript достаточно умный и присвоит переменным тип возвращаемого функциями значений

2023-04-23 21:46 UTC, vladDotH commented on client/src/components/common/map/api.ts
> +    return undefined;
если в функции нету return => возвращается undefined, можно его явно не возвращать

2023-04-23 21:47 UTC, vladDotH commented on client/src/components/common/map/MapDisplay.vue
> +let forestPolygonArr: number[][][] | undefined = await getForestPolygon(props.id);
но это не так важно...

2023-04-23 21:48 UTC, vladDotH requested changes

2023-04-23 21:48 UTC, vladDotH commented on server/app/routes/images_bp.py
> +    if (image_info is None):
вообще по-хорошему надо возвращать 404 в таких случаях

2023-04-24 11:23 UTC, Saprigenie commented on server/app/routes/images_bp.py
> +    if (image_info is None):
Исправил

2023-04-24 19:18 UTC, merged